[project]
name = "sampler"
version = "1.0.0"
description = "Sample files from based on config.yaml"
authors = [{ name = "Kyle Bloom", email = "kylejbloom@gmail.com" }]
requires-python = ">=3.10"
dependencies = ["pyyaml>=6.0"]
